FROM golang:1.25.0-alpine

WORKDIR /app

RUN mkdir -p /app/storage/original /app/storage/processed

# Установим Air и утилиты
RUN apk add --no-cache git && \
    go install github.com/air-verse/air@latest

# Копируем go.mod и go.sum и скачиваем зависимости
COPY go.mod go.sum ./
RUN go mod download

# Копируем весь код
COPY . .

RUN ls -la /app/config.yaml || echo "config.yaml not found"

# Air будет сам отслеживать изменения
CMD ["air", "-c", ".air.toml"]
